<?php
    // The following scripts and HTML will appear on each page.
    ini_set("display_errors",1);
    error_reporting(E_ALL);
    date_default_timezone_set("America/New_York");
    define('VMS_NON_INCLUDE', 1);
?>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="lib/jquery-1.9.1.js"></script>
        <link rel="stylesheet" href="css/base.css" type="text/css" />
        <script src="css/header.js"></script>
        <link rel="icon" type="image/x-icon" href="images/cropped-logo.png">