import mariadb

round1 = [
    ('an actor','un acteur','a male actor',None,1,['Professions', 'Art & Theater', 'Liaisons Ch. 7 Part 1']),
    ('an actress','une actrice','a female actor',None,2,['Professions', 'Art & Theater', 'Liaisons Ch. 7 Part 1']),
    ('a police officer','un agent de police','a male police officer',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female police officer','une agente de police','a police offer',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a social worker','un assistant social','a male social worker',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female social worker','une assistante sociale','a social worker',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a lawyer','un avocat','a male lawyer',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female lawyer','une avocate','a lawyer',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a singer','un chanteur','a male singer',None,1,['Art & Theatre', 'Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female singer','une chanteuse','a singer',None,2,['Art & Theatre', 'Professions', 'Liaisons Ch. 7 Part 1']),
    ('a hairdresser','un coiffeur','a hairstylist, a male hairdresser, a male hairstylist',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female hairdresser','une coiffeuse','a female hairstylist, a hairdresser, a hairstylist',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('an accountant','un comptable','a male accountant',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female accountant','une comptable','an accountant',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a cook','un cuisinier','a male cook',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female cook','une cuisinière','a cook',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a dentist','un dentiste','a male dentist',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female dentist','une dentiste','a dentist',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('an employee','un employé',None,None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female employee','une employée','an employee',None,2,['Professions', 'Workplace', 'Liaisons Ch. 7 Part 1']),
    ('a teacher','un enseignant','an instructor, a male teacher, a male instructor',None,1,['Professions', 'School & Education', 'Liaisons Ch. 7 Part 1']),
    ('a female instructor','une enseignante','a female teacher, an instructor, a teacher',None,2,['Professions', 'School & Education', 'Liaisons Ch. 7 Part 1']),
    ('a manager','un gérant','a male manager',None,1,['Professions', 'Workplace', 'Liaisons Ch. 7 Part 1']),
    ('a female manager','une gérante','a manager',None,2,['Professions', 'Workplace', 'Liaisons Ch. 7 Part 1']),
    ('a businessman',"un homme d'affaires",None,None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a businesswoman',"une femme d'affaires",None,None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a nurse','un infirmier','a male nurse',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female nurse','une infirmière','a nurse',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a computer specialist','un informaticien','a computer scientist, a male computer specialist, a male computer scientist',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female computer specialist','une informaticienne','a female computer scientist, a computer specialist, a computer scientist',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('an engineer','un ingénieur','a male engineer',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female engineer','une femme ingénieur',None,None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a journalist','un journaliste','a male journalist',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female journalist','une journaliste','a journalist',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a doctor','un médecin','a male doctor',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female doctor','une femme médecin',None,None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a musician','un musicien','a male musician',None,1,['Professions', 'Art & Theatre', 'Liaisons Ch. 7 Part 1']),
    ('a female musician','une musicienne','a musician',None,2,['Professions', 'Art & Theatre', 'Liaisons Ch. 7 Part 1']),
    ('a worker','un ouvrier','a factory work',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female worker','une ouvrière','a female factory worker',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a boss','un patron','a male boss',None,1,['Professions', 'Workplace', 'Liaisons Ch. 7 Part 1']),
    ('a female boss','une patronne','a boss',None,2,['Professions', 'Workplace', 'Liaisons Ch. 7 Part 1']),
    ('a plumber','un plombier','a male plumber',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female plumber','une femme plombier',None,None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a firefighter','un pompier','a male firefighter',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female firefighter','une femme pompier',None,None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a psychologist','un psychologue','a male psychologist',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female psychologist','une psychologue','a psychologist',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a secretary','un secrétaire','a male secretary',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female secretary','une secrétaire','a secretary',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a salesperson','un vendeur','a male salesperson, a salesman',None,1,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('a female salesperson','une vendeuse','a salesperson, a saleswoman',None,2,['Professions', 'Liaisons Ch. 7 Part 1']),
    ('to ask','demander',None,'demander à',0,['Verbs that take à', 'Liaisons Ch. 7 Part 1']),
    ('to give','donner',None,'donner à',0,['Verbs that take à', 'Liaisons Ch. 7 Part 1']),
    ('to send','envoyer',None,'envoyer à',0,['Verbs that take à', 'Liaisons Ch. 7 Part 1']),
    ('to earn','gagner','to win, to gain',None,0,['Verbs that take à', 'Liaisons Ch. 7 Part 1']),
    ('funny','amusant','amusing',None,1,['Personality', 'Liaisons Ch. P Part 3']),
    ('funny','amusante','amusing',None,2,['Personality', 'Liaisons Ch. P Part 3']),
    ('brilliant','brillant',None,None,1,['Personality', 'Liaisons Ch. P Part 3']),
    ('brilliant','brillante',None,None,2,['Personality', 'Liaisons Ch. P Part 3']),
    ('a classmate','un camarade de classe','a male classmate',None,1,['Personality', 'Liaisons Ch. P Part 2']),
    ('a female classmate','une camarade de classe','a classmate',None,2,['Personality', 'Liaisons Ch. P Part 2']),
    ('a class','une classe','a class of students',None,2,['Personality', 'Liaisons Ch. P Part 2']),
    ('a student','un étudiant','a male student',None,1,['Personality', 'Liaisons Ch. P Part 2']),
    ('a female student','une étudiante','a student',None,2,71),
    ('a poster','une affiche',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a stapler','une agrafeuse',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a desk','un bureau',None,None,1,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a notebook','un cahier',None,None,1,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a calculator','une calculatrice',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a chair','une chaise',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a classroom','une salle de classe',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a piece of chalk','une craie','a chalk, chalk',None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a pencil','un crayon',None,None,1,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a screen','un écran',None,None,1,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a window','une fenêtre',None,None,2,['Classroom/Office', 'Household', 'Liaisons Ch. P Part 2']),
    ('a piece of paper','une feuille de papier',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a clock','une horloge',None,None,2,['Classroom/Office', 'Workplace', 'Time', 'Liaisons Ch. P Part 2']),
    ('a book','un livre',None,None,1,['Classroom/Office', 'Art & Theatre', 'Liaisons Ch. P Part 2']),
    ('a computer','un ordinateur',None,None,1,['Classroom/Office', 'Technology,' 'Liaisons Ch. P Part 2']),
    ('a laptop','un ordinateur portable','a laptop computer',None,1,['Classroom/Office', 'Technology', 'Liaisons Ch. P Part 2']),
    ('a door','une porte',None,None,2,['Classroom/Office', 'Household', 'Liaisons Ch. P Part 2']),
    ('a waste basket','une poubelle','a trashcan',None,2,['Classroom/Office', 'Household', 'Liaisons Ch. P Part 2']),
    ('a bag','un sac','a purse',None,1,['Classroom/Office', 'Clothing & Style', 'Liaisons Ch. P Part 2']),
    ('a backpack','un sac à dos','a bookbag',None,1,['Classroom/Office', 'School & Education', 'Liaisons Ch. P Part 2']),
    ('a pen','un stylo',None,None,1,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a table','une table',None,None,2,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a chalkboard','un tableau',None,None,1,['Classroom/Office', 'Liaisons Ch. P Part 2']),
    ('a cellphone','un portable','a phone, a cell phone','un téléphone portable',1,['Classroom/Office', 'Technology', 'Liaisons Ch. P Part 2']),
    # we stop here
]

def get_database():
    return mariadb.connect(user='undertoe', password='vXXtbewgyyWHMXuqc5nmKN29zk9yaxiM5zJy4CfPf4x85j138hzvEpw9d42HpIp1', host='localhost', port=3306, database='etudamie')

connection = get_database()
cursor = connection.cursor()

cursor.execute('select id, name from category')
category_ids = {}
for category in cursor.fetchall():
    id, name = category
    category_ids[name] = id 

def category_create(category_name, cursor):
    cursor.execute('insert into category (sortindex, name, ischapter) values (default, ?, ?)', (category_name, category_name.startswith('Liaisons Ch')))
    return cursor.lastrowid
for entry in round1:
    # english, french, english alts, french alts, gender (0/1/2), [Categories]
    english, french, english_alts, french_alts, gender, categories = entry
    ids = []
    for category in categories:
        if category not in category_ids:
            cid = category_create(category, cursor)  
            category_ids[category] = cid
        else:
            ids.append(category_ids[category])
    cursor.execute('insert into term (english, french, englishAlt, frenchAlt, gender) values (?, ?, ?, ?, ?)', (english, french, english_alts, french_alts, gender))
    term_id = cursor.lastrowid
    for category, category_id in category_ids:
        cursor.execute('insert into termInCategory (termid, categoryid) values (?, ?)', (term_id, category_id))

connection.commit()
connection.close()

remaining = [
    ('to earn money',"gagner de l'argent",'to gain money, to win money',None,0,57),
    ('to earn a living','gagner sa vie','to make a living',None,0,58),
    ('to show','montrer',None,'montrer à',0,59),
    ('to pose','poser','to put','poser à',0,60),
    ('to ask a question','poser une question',None,'poser une question à',0,61),
    ('to lend','prêter',None,'prêter à',0,62),
    ('a career','une carrière',None,None,2,117),
    ('a job','un emploi',None,None,1,118),
    ('a company','une entreprise',None,None,2,119),
    ('a position','un poste',None,None,1,120),
    ('a profession','une profession',None,None,2,121),
    ('a salary','un salaire','pay, wages',None,1,122),
    ('work','le travail','the work',None,1,123),
    ('someone',"quelqu'un",None,None,0,124),
    ('to have good communication skills','avoir de bonnes capacités de communication',None,None,0,125),
    ('to have a good work ethic','avoir le goût du travail',None,None,0,126),
    ('to have a sense of humor',"avoir le sens de l'humour",None,None,0,127),
    ('to be good with numbers','être bon avec les chiffres',None,None,1,128),
    ('to be good with numbers','être bonne avec les chiffres',None,None,2,129),
    ('to be in a good mood','être de bonne humeur',None,None,0,130),
    ('to be in a bad mood','être de mauvaise humeur',None,None,0,131),
    ('to be a morning person','être du matin',None,None,0,132),
    ('to be precise','être précis',None,None,1,133),
    ('to be precise','être précise',None,None,2,134),
    ('to be a night person','être du soir',None,None,0,135),
    ('uptight','coincé',None,None,1,136),
    ('uptight','coincée',None,None,2,137),
    ('creative','créatif',None,None,1,138),
    ('creative','créative',None,None,2,139),
    ('disloyal','déloyal',None,None,1,140),
    ('disloyal','déloyale',None,None,2,141),
    ('funny','drôle','odd, oddly funny',None,0,142),
    ('demanding','exigeant',None,None,1,143),
    ('demanding','exigeante',None,None,2,144),
    ('flexible','flexible',None,None,0,145),
    ('inflexible','inflexible',None,None,0,146),
    ('jealous','jaloux',None,None,1,147),
    ('jealous','jalouse',None,None,2,148),
    ('loyal','loyal',None,None,1,149),
    ('loyal','loyale',None,None,2,150),
    ('organized','organisé',None,None,1,151),
    ('organized','organisée',None,None,2,152),
    ('sensitive','sensible',None,None,0,153),
    ('stubborn','têtu',None,None,1,154),
    ('stubborn','têtue',None,None,2,155),
    ('competitive','acharné','cutthroat',None,1,156),
    ('competitive','acharnée','cutthroat',None,2,157),
    ('eccentric','excentrique',None,None,0,158),
    ('extroverted','extraverti','extrovert, extraverted',None,1,159),
    ('extroverted','extravertie','extravert, extraverted',None,2,160),
    ('scatter-brained','farfelu',None,None,1,161),
    ('scatter-brained','farfelue',None,None,2,162),
    ('introverted','introverti','introvert',None,1,163),
    ('introverted','introvertie','introvert',None,2,164),
    ('professional','professionnel',None,None,1,165),
    ('professional','professionnelle',None,None,2,166),
    ('to have to','devoir','must, to owe',None,0,167),
    ('to be able','pouvoir','can',None,0,168),
    ('to want','vouloir',None,None,0,169),
    ('an end-of-high-school exam','un baccalauréat','an end of high school exam',None,1,170),
    ('a middle school','un collège','a junior high school',None,1,171),
    ('a diploma','un diplôme',None,None,1,172),
    ('a university diploma','un diplôme universitaire',None,None,1,173),
    ('a doctorat','un doctorat','a Ph.D.',None,1,174),
    ('higher education','les études supérieures','the higher education',None,2,175),
    ("an equivalent of a bachelor's degree",'une licence',"a French bachelor's degree",None,2,176),
    ('a high school','un lycée',None,None,1,177),
    ("a master's degree",'un master',None,None,1,178),
    ('an MBA','un MBA',None,None,1,179),
    ('an internship','un stage de formation',None,None,1,180),
    ('a business school','une école de commerce',None,None,2,181),
    ('a vocational school','une école professionnelle','a trade school, a professional school',None,2,182),
    ('a law school','une faculté de droit',None,None,2,183),
    ('a liberal arts school','une faculté de lettres et de sciences humaines','a liberal arts college',None,2,184),
    ('a medical school','une faculté de médecine','a med school',None,2,185),
    ('a science and technology school','une faculté de sciences et de technologie','a science and technology college',None,2,186),
    ('bills','les billets','banknotes, the bills, the banknotes',None,1,187),
    ('a scholarship',"une bourse d'études",None,None,2,188),
    ('a debit card','une carte bancaire',None,None,2,189),
    ('a checking account','un compte-chèques',None,None,1,190),
    ('an ATM','un distributeur automatique',None,None,1,191),
    ('tuition','les frais de scolarité',None,None,1,192),
    ('coins','les pièces de monnaie',None,None,2,193),
    ('a student loan','un prêt étudiant',None,None,1,194),
    ('to spend','dépenser',None,None,0,195),
    ('to spend money','dépenser de l''argent',None,None,0,196),
    ('to deposit','déposer',None,None,0,197),
    ('to deposit money','déposer de l''argent',None,None,0,198),
    ('to borrow','emprunter',None,None,0,199),
    ('to save money','faire des économies',None,None,0,200),
    ('to pay by check','payer par chèque','to pay with check',None,0,201),
    ('to pay back','rembourser',None,None,0,202),
    ('to withdraw money','retirer de l''argent',None,None,0,203),
    ('I can','je peux','I am able to, I''m able to','',0,206),
    ('you can (informal)','tu peux','you''re able to, you are able to','',0,207),
    ('he can','il peut','he''s able to, he is able to',None,0,208),
    ('we can','nous pouvons','we are able to, we''re able to','on peut',0,209),
    ('you can (formal)','vous pouvez','you are able to, you''re able to',None,0,210),
    ('they can','ils peuvent','they''re able to, they are able to',None,0,211),
    ('I must','je dois','I have to',None,0,212),
    ('you must (informal)','tu dois','you have to',None,0,213),
    ('he must','il doit','he has to',None,0,214),
    ('we must','nous devons','we have to','on doit',0,215),
    ('you must (formal)','vous devez','you have to',None,0,216),
    ('they must','ils doivent','they have to','elles doivent',0,217),
    ('I want','je veux',None,None,0,218),
    ('you want (informal)','tu veux',None,None,0,219),
    ('he wants','il veut',None,None,0,220),
    ('we want','nous voulons',None,'on veut',0,221),
    ('you want (formal)','vous voulez',None,None,0,222),
    ('they want','ils veulent',None,'elles veulent',0,223),
    ('to have wanted','avoir vulu',None,None,0,224),
    ('to have had to','avoir dû',None,None,0,225),
    ('to have been able to','avoir pu',None,None,0,226),
    ('a writer','un écrivain','a male writer',None,1,227),
    ('a female writer','une écrivaine','a writer',None,2,228),
    ('an emperor','un empereur','a male emperor',None,1,229),
    ('an empress','une impératrice','a female emperor',None,2,230),
    ('an explorer','un explorateur','a male explorer',None,1,231),
    ('a female explorer','une exploratrice','an explorer',None,2,232),
    ('a general','un général',None,None,1,233),
    ('a hero','un héros',None,None,1,234),
    ('a heroine','une héroïne',None,None,2,235),
    ('a male politician','un homme politique',None,None,1,236),
    ('a female politician','une femme politique',None,None,2,237),
    ('a poet','un poète','a male poet',None,1,238),
    ('a female poet','une femme poète',None,None,2,239),
    ('a prime minister','un premier ministre',None,None,1,240),
    ('a president','un président',None,None,1,241),
    ('a king','un roi',None,None,1,242),
    ('a queen','une reine',None,None,2,243),
    ('a soldier','un soldat','a male soldier',None,1,244),
    ('a female soldier','une femme soldat',None,None,2,245),
    ('a colony','une colonie',None,None,2,246),
    ('an empire','un empire',None,None,1,247),
    ('a war','une guerre','','',2,248),
    ('against','contre',None,None,0,249),
    ('independence','l''indépendance','the independence',None,2,250),
    ('a freedom','une liberté',None,None,2,251),
    ('a monarchy','une monarchie',None,None,2,252),
    ('a political movement','un mouvement','a movement',None,1,253),
    ('nationalism','le nationalisme','the nationalism',None,1,254),
    ('peace','la paix','the peace',None,2,255),
    ('a reform','une réforme',None,None,2,256),
    ('a revolution','une révolution',None,None,2,257),
    ('tolerance','la tolérance','the tolerance',None,2,258),
    ('colonisation','la colonisation','the colinisation','',2,259),
    ('decolonisation','la décolonisation','the decolonisation',None,2,260),
    ('a period','une époque','a time',None,2,261),
    ('contemporary','contemporain',None,None,1,262),
    ('contemporary','contemporaine',None,None,2,263),
    ('to help','aider','to aid',None,0,264),
    ('to found','fonder',None,None,0,265),
    ('at that time','à cette époque-là','in those days',None,0,266),
    ('in the past','autrefois','long ago',None,0,267),
    ('each','chaque',None,None,0,268),
    ('usually','d''habitude',None,None,0,269),
    ('memorable','marquant','important',None,1,270),
    ('memorable','marquante','important','',2,271),
    ('peaceful','pacifique',None,None,0,272),
    ('a birthday','un anniversaire','an anniversary',None,1,273),
    ('a wedding anniversary','un anniversaire de mariage','an anniversary',None,1,274),
    ('Mother''s Day','la fête des Mères',None,None,2,275),
    ('Father''s Day','la fête des Pères',None,None,2,276),
    ('Labor Day','la fête du Travail',None,None,2,277),
    ('Hanukah','Hanoukka',None,None,0,278),
    ('Thanksgiving','le jour de l''Action de Grâce',None,None,1,279),
    ('New Year''s Day','le jour de l''An','New Year''s',None,1,280),
    ('Mardi Gras','Mardi gras',None,None,0,281),
    ('Christmas','Noël',None,None,0,282),
    ('Easter','Pâques',None,None,0,283),
    ('April Fools'' Day','le poisson d''avril','April first','le premier avril',1,284),
    ('New Year''s Eve','la Saint-Sylvestre',None,None,2,285),
    ('Valentine''s Day','la Saint-Valentin','St. Valentine''s Day, Saint Valentine''s Day',None,2,286),
    ('Christmas Eve','la veille de Noël',None,None,2,287),
    ('a gift','un cadeau',None,None,1,288),
    ('a greeting card','une carte de vœux',None,None,2,289),
    ('a holiday','une fête','party, celebration','',2,290),
    ('a legal holiday','un jour férié',None,None,1,291),
    ('an evening party','une soirée','a party',None,2,292),
    ('Happy birthday!','Bon anniversaire!',None,'Joyeux anniversaire!',0,293),
    ('Happy New Year!','Bonne année!',None,None,0,294),
    ('Congratulations!','Félicitations!',None,None,0,295),
    ('Best wishes!','Meilleurs vœux!',None,None,0,296),
    ('to celebrate','fêter',None,None,0,297),
    ('to organize a party','organiser une fête','to throw a party',None,0,298),
    ('once','une fois','','',2,299),
    ('suddenly','soudain',None,None,0,300),
    ('all of a sudden','tout d''un coup',None,None,0,301),
    ('first','premier',None,None,1,302),
    ('first','première',None,None,2,303),
    ('fourth','quatrième',None,None,0,304),
    ('fifth','cinquième',None,None,0,305),
    ('ninth','neuvième',None,None,0,306),
    ('twenty-first','vingt-et-unième',None,None,0,307),
    ('thirty-first','trente-et-unième',None,None,0,308),
    ('seventy-fifth','soixante-quinzième',None,None,0,309),
    ('hundredth','centième',None,None,0,310),
    ('art','l''art','the art','art',1,311),
    ('a language','une langue',None,None,2,312),
    ('German','l''allemand',None,None,1,313),
    ('English','l''anglais',None,None,1,314),
    ('Chinese','le chinois',None,None,1,315),
    ('Spanish','l''espagnol',None,None,1,316),
    ('French','le français',None,None,1,317),
    ('Russian','le russe',None,None,1,318),
    ('literature','la littérature','the literature',None,2,319),
    ('music','la musique','the music','musique',2,320),
    ('philosophy','la philosophie','the philosophy','philosophie',2,321),
    ('adolescence','l''adolescence',None,None,2,322),
    ('adulthood','l''âge adulte',None,None,1,323),
    ('childhood','l''enfance',None,None,2,324),
    ('a stage','une étape',None,None,2,325),
    ('a stage of life','une étape de la vie',None,None,2,326),
    ('youth','la jeunesse','','',2,327),
    ('old age','la vieillesse',None,None,2,328),
    ('a baptism','un baptême',None,None,1,329),
    ('a graduation ceremony','une cérémonie de remise des diplômes',None,None,2,330),
    ('a death','un décès',None,None,1,331),
    ('a divorce','un divorce',None,None,1,332),
    ('a burial','un enterrement','a funeral',None,1,333),
    ('engagement','les fiançailles',None,None,2,334),
    ('a marriage','un mariage',None,None,1,335),
    ('a birth','une naissance',None,None,2,336),
    ('retirement','la retraite',None,None,2,337),
    ('a honeymoon','un voyage de noces',None,None,1,338),
    ('an adolescent','un adolescent','a male adolescent',None,1,339),
    ('a female adolescent','une adolescente','an adolescent',None,2,340),
    ('an adult','un adulte','a male adult','',1,341),
    ('a female adult','une adulte','an adult',None,2,342),
    ('love at first sight','le coup de foudre',None,None,1,343),
    ('a couple','un couple',None,None,1,344),
    ('a spouse','un époux','a male spouse',None,1,345),
    ('a female spouse','une épouse','a spouse',None,2,346),
    ('newly weds','les nouveaux mariés',None,None,0,347),
    ('a relationship','une relation',None,None,2,348),
    ('a date','un rendez-vous','an appointment',None,1,349),
    ('a banquet','un banquet',None,None,1,350),
    ('a reception','une réception','a formal reception',None,2,351),
    ('Good luck!','Bonne chance!',None,None,0,352),
    ('happiness','le bonheur',None,None,1,353),
    ('condolences','les condoléances',None,None,2,354),
    ('Happy retirement!','Bonne retraite!',None,None,0,355),
    ('success','la réussite',None,None,2,356),
    ('to be familiar with','connaître','to know',None,0,357),
    ('to know','savoir','to know how to, to know by heart',None,0,358),
    ('to retire','prendre sa retraite','to retire from a job',None,0,359),
    ('to dream','rêver',None,None,0,360),
    ('to fall in love','tomber amoureux','','',1,361),
    ('to fall in love','tomber amoureuse',None,None,2,362),
    ('to stash','remiser','to put away',None,0,363),
    ('January','janvier',None,None,0,364),
    ('February','février',None,None,0,365),
    ('March','mars',None,None,0,366),
    ('April','avril',None,None,0,367),
    ('May','mai',None,None,0,368),
    ('June','juin',None,None,0,369),
    ('July','juillet',None,None,0,370),
    ('August','août',None,None,0,371),
    ('September','septembre',None,None,0,372),
    ('October','octobre',None,None,0,373),
    ('November','novembre',None,None,0,374),
    ('December','décembre',None,None,0,375),
    ('a year','un an',None,None,1,376),
    ('a year','une année',None,None,2,377),
    ('a month','un mois',None,None,1,378),
    ('a season','une saison',None,None,2,379),
    ('fall','l''automne','Fall, autumn',None,1,380),
    ('summer','l''été',None,None,1,381),
    ('winter','l''hiver',None,None,1,382),
    ('spring','le printemps',None,None,1,383),
    ('a star','une étoile',None,None,2,384),
    ('moon','la lune','the moon',None,2,385),
    ('weather forecast','la météo',None,None,2,386),
    ('snow','la neige',None,None,2,387),
    ('clouds','des nuages','some clouds',None,1,388),
    ('rain','la pluie',None,None,2,389),
    ('sun','le soleil',None,None,1,390),
    ('tornado','la tornade',None,None,2,391),
    ('What''s the temperature?','Quelle température fait-il?',None,None,0,392),
    ('It''s 20 degrees.','Il fait 20 degrés.','It''s 20 degrees Celsius.',None,0,393),
    ('What''s the weather like?','Quel temps fait-il?',None,None,0,394),
    ('It''s nice out.','Il fait beau.','The weather is nice.',None,0,395),
    ('It''s hot.','Il fait chaud.',None,None,0,396),
    ('It''s cool.','Il fait frais.',None,None,0,397),
    ('It''s cold.','Il fait froid.',None,None,0,398),
    ('It''s dreary.','It fait gris.',None,None,0,399),
    ('It''s hot and muggy.','Il fait lourd.',None,None,0,400),
    ('The weather is bad.','Il fait mauvais.',None,None,0,401),
    ('It''s sunny.','Il fait du soleil.',None,'Il fait soleil.',0,402),
    ('It''s windy.','Il fait du vent.',None,None,0,403),
    ('It''s snowing.','Il neige.',None,None,0,404),
    ('It''s raining.','Il pleut.',None,None,0,405),
    ('It''s cloudy.','Le ciel est couvert.','It''s overcast.',None,0,406),
    ('What''s the date?','Quelle est la date?','What''s the date today?','Quelle est la date aujourd''hui?',0,407),
    ('It''s May first.','C''est le premier mai.',None,None,0,408),
    ('It''s the 10th of November.','C''est le 10 novembre.','It''s November 10th.','On est le 10 novembre., Nous sommes le 10 novembre.',0,409),
    ('When is your birthday?','C''est quand ton anniversaire?','When''s your birthday?','C''est quand votre anniversaire?',0,410),
    ('When is Samir''s birthday?','C''est quand l''anniversaire de Samir?',None,None,0,411),
    ('for how long','depuis combien de temps',None,None,0,412),
    ('for','pour',None,None,0,413),
    ('to go','aller',None,None,0,414),
    ('to forecast','annoncer',None,None,0,415),
    ('baseball','le baseball',None,None,1,416),
    ('basketball','le basket-ball',None,'le basket',1,417),
    ('soccer','le football',None,'le foot',1,418),
    ('football','le football américain','American football',None,1,419),
    ('golf','le golf',None,None,1,420),
    ('hockey','le hockey',None,None,1,421),
    ('rugby','le rugby',None,None,1,422),
    ('tennis','le tennis',None,None,1,423),
    ('ping-pong','le tennis de table','ping pong, table tennis',None,1,424),
    ('volleyball','le volley-ball',None,None,1,425),
    ('to do','faire','to make',None,0,426),
    ('to do aerobics','faire de l''aérobic',None,None,0,427),
    ('to go bowling','faire du bowling',None,None,0,428),
    ('to go horseback riding','faire du cheval',None,None,0,429),
    ('to workout','faire de la gym','to exercise','faire du sport',0,430),
    ('to go jogging','faire du jogging',None,None,0,431),
    ('to walk for exercise','faire de la marche',None,None,0,432),
    ('to swim for exercise','faire de la natation',None,None,0,433),
    ('to ice-skate','faire du patinage','to go ice-skating',None,0,434),
    ('to go wind-surfing','faire de la planche à voile',None,None,0,435),
    ('to go downhill skiing','faire du ski alpin',None,None,0,436),
    ('to go cross-country skiing','faire du sku de fond',None,None,0,437),
    ('to water-ski','faire du ski nautique','to go water-skiing',None,0,438),
    ('to surf','faire du surf',None,None,0,439),
    ('to go bike riding','faire du vélo','to go biking',None,0,440),
    ('to do yoga','faire du yoga',None,None,0,441),
    ('to play','jouer',None,None,0,442),
    ('to play tennis','jouer au tennis',None,None,0,443),
    ('to practice','pratiquer','to play a sport, to do a sport',None,0,444),
    ('a team','une équipe',None,None,2,445),
    ('a player','un joueur',None,None,1,446),
    ('a player','une joueuse',None,None,2,447),
    ('a game','un match',None,None,1,448),
    ('a tennis match','un match du tennis',None,None,1,449),
    ('to say','dire',None,None,0,450),
    ('to write','écrire',None,None,0,451),
    ('to read','lire',None,None,0,452),
    ('life','la vie',None,None,2,453),
    ('absolutely','absolument','','',0,454),
    ('actively','activement',None,None,0,455),
    ('constantly','constamment',None,None,0,456),
    ('fluently','couramment',None,None,0,457),
    ('evidently','évidemment',None,None,0,458),
    ('nicely','gentiment','','',0,459),
    ('slowly','lentement',None,None,0,460),
    ('patiently','patiemment',None,None,0,461),
    ('politely','poliment',None,None,0,462),
    ('seriously','sérieusement',None,None,0,463),
    ('truly','vraiment','really',None,0,464),
    ('well','bien',None,None,0,465),
    ('badly','mal','poorly',None,0,466),
    ('quickly','vite','fast, hurry!','rapidement',0,467),
    ('to go to the spa','aller au spa',None,None,0,468),
    ('to order a pizza','commander une pizza',None,None,0,469),
    ('to draw','dessiner','to sketch',None,0,470),
    ('to write letters','écrire des lettres',None,None,0,471),
    ('to write text messages','écrire des textos',None,None,0,472),
    ('to have a barbecue','faire un barbecue','to have a BBQ',None,0,473),
    ('to tinker','faire du bricolage','to do odd jobs, to act the handyman, to act the handywoman',None,0,474),
    ('to go camping','faire du camping',None,None,0,475),
    ('to run some errands','faire les courses','to run errands',None,0,476),
    ('to cook','faire la cuisine',None,None,0,477),
    ('to do classical dance','faire de la danse classique',None,None,0,478),
    ('to do modern dance','faire de la danse moderne',None,None,0,479),
    ('to party','faire la fête',None,None,0,480),
    ('to sleep in','faire la grasse matinée',None,None,0,481),
    ('to garden','faire du jardinage',None,None,0,482),
    ('to practice photography','faire de la photo',None,'faire de la photographie',0,483),
    ('to have a picnic','faire un pique-nique','to go on a picnic',None,0,484),
    ('to take a walk','faire une promenade',None,None,0,485),
    ('in town','en ville',None,None,0,486),
    ('to shop','faire du shopping','to go shopping',None,0,487),
    ('to take a nap','faire la sieste',None,None,0,488),
    ('to take a trip','faire un voyage',None,None,0,489),
    ('to play cards','jouer aux cartes',None,None,0,490),
    ('to play board games','jouer aux jeux de société',None,None,0,491),
    ('to play the drums','jouer de la batterie',None,None,0,492),
    ('to play the guitar','jouer de la guitare',None,None,0,493),
    ('to play music','jouer de la musique',None,None,0,494),
    ('to play the piano','jouer du piano','to play piano',None,0,495),
    ('to play the violin','jouer du violon','to play violin',None,0,496),
    ('to play the cello','jouer du violoncelle','to play cello',None,0,497),
    ('to read e-mails','lire les courriels','to read e-mail',None,0,498),
    ('to read the newspaper','lire le journal',None,None,0,499),
    ('to read a novel','lire un roman',None,None,0,500),
    ('a leisure activity','un loisir','a leisure',None,1,501),
    ('a pastime','un passe-temps','a hobby',None,1,502),
    ('a pleasure','un plaisir',None,None,1,503),
    ('the sixties','les années 60',None,None,0,504),
    ('wealth','la richesse',None,None,2,505),
    ('change','le changement',None,None,1,506),
    ('tranquillity','la tranquillité','peace and quiet',None,2,507),
    ('a dispute','une dispute',None,None,2,508),
    ('a conflict','un conflit',None,None,1,509),
    ('continent','le continent',None,None,1,510),
    ('country','le pays',None,None,1,511),
    ('North Africa','l''Afrique du Nord',None,None,2,512),
    ('West Africa','l''Afrique de l''Ouest',None,None,2,513),
    ('Germany','l''Allemagne',None,None,2,514),
    ('North America','l''Amérique du Nord',None,None,2,515),
    ('South Africa','l''Amérique du Sud',None,None,2,516),
    ('England','l''Angleterre',None,None,2,517),
    ('Asia','l''Asie',None,None,2,518),
    ('Belgium','la Belgique',None,None,2,519),
    ('Brazil','le Brésil',None,None,1,520),
    ('Canada','le Canada',None,None,1,521),
    ('China','la Chine',None,None,2,522),
    ('Ivory Coast','la Côte d''Voire',None,None,2,523),
    ('Spain','l''Espagne','','',2,524),
    ('United States','les États-Unis','The United States',None,1,525),
    ('Europe','l''Europe',None,None,2,526),
    ('Eastern Europe','l''Europe de l''Est',None,None,2,527),
    ('Western Europe','l''Europe de l''Ouest',None,None,2,528),
    ('France','la France',None,None,2,529),
    ('Ireland','l''Irlande',None,None,2,530),
    ('Italy','l''Italie',None,None,2,531),
    ('Japan','le Japon',None,None,1,532),
    ('Morocco','le Maroc',None,None,1,533),
    ('Mexico','le Mexique',None,None,1,534),
    ('Quebec','le Québec',None,None,1,535),
    ('Romania','la Roumanie',None,None,2,536),
    ('Russia','la Russie',None,None,2,537),
    ('Senegal','le Sénégal',None,None,1,538),
    ('Switzerland','la Suisse',None,None,2,539),
    ('Tunisia','la Tunisie',None,None,2,540),
    ('Vietnam','le Viêt-Nam',None,None,1,541),
    ('California','la Californie','','',2,542),
    ('North Carolina','la Caroline du Nord',None,None,2,543),
    ('South Carolina','la Caroline du Sud',None,None,2,544),
    ('North Dakota','le Dakota du Nord',None,None,1,545),
    ('South Dakota','le Dakota du Sud',None,None,1,546),
    ('New York','l''état de New York','New York state',None,1,547),
    ('Washington','l''état de Washington','Washington state',None,1,548),
    ('Florida','la Floride',None,None,2,549),
    ('Georgia','la Géorgie',None,None,2,550),
    ('Louisiana','la Louisiane',None,None,2,551),
    ('New Mexico','le Nouveau-Mexique',None,None,1,552),
    ('Pennsylvania','la Pennsylvania',None,None,2,553),
    ('Virginia','la Virginie',None,None,2,554),
    ('West Virginia','la Virginie Occidentale',None,None,2,555),
    ('to become','devenir',None,None,0,556),
    ('to come','venir',None,None,0,557),
    ('to come from','venir de','to have just done something',None,0,558),
    ('National Holiday','la fête nationale',None,None,2,559),
    ('fine arts','les beaux-arts',None,None,1,560),
    ('a masterpiece','un chef-d''œuvre',None,None,1,561),
    ('a drawing','un dessin',None,None,1,562),
    ('a still life painting','une nature morte','a still life',None,2,563),
    ('a work of art','une œuvre d''art',None,None,2,564),
    ('a landscape','un paysage',None,None,1,565),
    ('a photograph','une photographie','a photo','une photo',2,566),
    ('pop art','le pop art',None,None,1,567),
    ('a portrait','un portrait','','',1,568),
    ('a sculpture','une sculpture',None,None,2,569),
    ('a tapestry','une tapisserie',None,None,2,570),
    ('an artist','un artiste','a male artist',None,1,571),
    ('a female artist','une artiste','an artist',None,2,572),
    ('a painter','un peintre','a male painter',None,1,573),
    ('a female painter','une peintre','a painter',None,2,574),
    ('a photographer','un photographe','a male photographer',None,1,575),
    ('a female photographer','une photographe','a photographer',None,2,576),
    ('a sculptor','un sculpteur','a male sculptor','',1,577),
    ('a female sculptor','une sculptrice','a sculptor',None,2,578),
    ('an exhibition','une exposition',None,None,2,579),
    ('an art gallery','une galerie d''art',None,None,2,580),
    ('subject','le sujet',None,None,1,581),
    ('style','le style',None,None,1,582),
    ('to paint','faire de la peinture',None,None,0,583),
    ('to sculpt','faire de la sculpture',None,None,0,584),
    ('to photograph','photographier',None,None,0,585),
    ('abstract','abstrait',None,None,1,586),
    ('abstract','abstraite',None,None,2,587),
    ('cubist','cubiste',None,None,0,588),
    ('impressionist','impressionniste',None,None,0,589),
    ('modern','moderne',None,None,0,590),
    ('somber','sombre','dark',None,0,591),
    ('surrealist','surréaliste',None,None,0,592),
    ('lively','vif','bright, colorful','',1,593),
    ('lively','vive','bright, colorful',None,2,594),
    ('a ballet','un ballet',None,None,1,595),
    ('a song','une chanson',None,None,2,596),
    ('a choir','un chœur',None,None,1,597),
    ('a choir','une chorale',None,None,2,598),
    ('a musical','une comédie musicale',None,None,2,599),
    ('a composer','un compositeur','a male composer',None,1,600),
    ('a female composer','une femme compositeur','a composer','une compositrice',2,601),
    ('a concert','un concert',None,None,1,602),
    ('a dancer','un danseur','a male dancer',None,1,603),
    ('a female dancer','une danseuse','a dancer',None,2,604),
    ('an opera','un opéra',None,None,1,605),
    ('an orchestra','un orchestre',None,None,1,606),
    ('a play','une pièce de théâtre',None,None,2,607),
    ('a performance','un spectacle','a show',None,1,608),
    ('an author','un auteur','a male author',None,1,609),
    ('a female author','une femme auteur',None,None,2,610),
    ('a tale','un conte',None,None,1,611),
    ('a fairy tale','un conte de fées','a fairytale',None,1,612),
    ('a critic','un critique','a male critic',None,1,613),
    ('a critique','une critique','a review, a female critic',None,2,614),
    ('beginning','le début',None,None,1,615),
    ('end','la fin','ending',None,2,616),
    ('a genre','un genre',None,None,1,617),
    ('blues','le blues',None,None,1,618),
    ('R&B','le R''n''B','R & B, R and B',None,1,619),
    ('hip-hop','le hip-hop','hip hop',None,1,620),
    ('jazz','le jazz',None,None,1,621),
    ('alternative music','la musique alternative','alternative',None,2,622),
    ('classical music','la musique classique','classic',None,2,623),
    ('country music','la musique country','country','la country',2,624),
    ('folk music','la musique folk','folk',None,2,625),
    ('world music','les musiques du monde',None,None,2,626),
    ('new age music','la musique new age','new age',None,2,627),
    ('pop','la pop','pop music',None,2,628),
    ('rap','le rap','rap music',None,1,629),
    ('rock','le rock','rock music',None,1,630),
    ('literary','littéraire',None,None,0,631),
    ('poetic','poétique',None,None,0,632),
    ('recent','récent',None,None,1,633),
    ('recent','récente',None,None,2,634),
    ('to applaud','applaudir',None,None,0,635),
    ('to publish','publier',None,None,0,636),
    ('to live','vivre',None,None,0,637),
    ('a comedy','une comédie',None,None,2,638),
    ('a documentary','un documentaire',None,None,1,639),
    ('a drama','un drame',None,None,1,640),
    ('a psychological drama','un drame psychologique',None,None,1,641),
    ('an action film','un film d''action',None,None,1,642),
    ('a romance film','un film romantique',None,None,1,643),
    ('a horror film','un film d''horreur',None,None,1,644),
    ('a suspense film','un film à suspense',None,None,1,645),
    ('a sci-fi film','un film de science-fiction',None,None,1,646),
    ('a crime film','un policier','a detective film',None,1,647),
    ('a western','un western',None,None,1,648),
    ('a talk show','une causerie','a talkshow',None,2,649),
    ('a cartoon','un dessin animé',None,None,1,650),
    ('an animated film','un film d''animation',None,None,1,651),
    ('a broadcast','une émission','a TV show',None,2,652),
    ('a culinary program','une émission culinaire','a cooking show',None,2,653),
    ('a shopping network show','une émission de téléachat','an informercial',None,2,654),
    ('a reality TV show','une émission de téléréalité',None,None,2,655),
    ('a soap opera','un feuilleton',None,None,1,656),
    ('news broadcast','les informations','news','les infos',2,657),
    ('a televised game','un jeu télévisé',None,None,1,658),
    ('news','les nouvelles',None,None,2,659),
    ('a commercial','une publicité',None,'une pub',2,660),
    ('a sitcom','une série','a TV drama',None,2,661),
    ('a character','un personnage',None,None,1,662),
    ('a director','un réalisateur','a male director',None,1,663),
    ('a female director','une réalisatrice','a director',None,2,664),
    ('a role','un rôle',None,None,1,665),
    ('to believe','croire',None,None,0,666),
    ('to receive','recevoir',None,None,0,667),
    ('to see again','revoir',None,None,0,668),
    ('to see','voir',None,None,0,669),
    ('a shopping addict','un accro du shopping',None,None,1,670),
    ('stingy','avare','miserly',None,0,671),
    ('talkative','bavard','gossipy',None,1,672),
    ('talkative','bavarde','gossipy',None,2,673),
    ('stupid','bête','idiotic',None,0,674),
    ('well-dressed','bien habillé',None,None,1,675),
    ('well-dressed','bien habillée',None,None,2,676),
    ('poorly-dressed','mal habillé',None,None,1,677),
    ('poorly-dressed','mal habillée',None,None,2,678),
    ('selfish','égoïste',None,None,0,679),
    ('loyal','fidèle',None,None,0,680),
    ('disloyal','infidèle',None,None,0,681),
    ('graceful','gracieux','gracious',None,1,682),
    ('graceful','gracieuse','gracious',None,2,683),
    ('clumsy','maladroit',None,None,1,684),
    ('clumsy','maladroite',None,None,2,685),
    ('pretentious','prétentieux',None,None,1,686),
    ('pretentious','prétentieuse',None,None,2,687),
    ('simple','simple',None,None,0,688),
    ('tolerant','tolérant',None,None,1,689),
    ('tolerant','tolérante',None,None,2,690),
    ('a bourgeois bohemian','un bobo',None,None,1,691),
    ('a workaholic','un bourreau de travail',None,None,1,692),
    ('single people','les célibataires',None,None,1,693),
    ('to love oneself','s''aimer','to love each other',None,0,694),
    ('friendship','l''amitié',None,None,2,695),
    ('love','l''amour',None,None,1,696),
    ('environment','l''environnement','the environment',None,1,697),
    ('loyalty','la fidélité','fidelity',None,2,698),
    ('infidelity','l''infidélité','disloyalty',None,2,699),
    ('morality','la moralité',None,None,2,700),
    ('prestige','le prestige',None,None,1,701),
    ('spirituality','la spiritualité',None,None,2,702),
    ('success','le succès',None,None,1,703),
    ('environmentalists','les écologistes','ecologists','les écolos',0,704),
    ('health nuts','les fanas de la santé',None,None,0,705),
    ('housewives','les femmes au foyer',None,None,2,706),
    ('househusbands','les hommes au foyer',None,None,1,707),
    ('hippies','les hippies',None,None,0,708),
    ('jet setters','les membres de la jet-set',None,None,0,709),
    ('a working mom','une mère active','a working mother',None,2,710),
    ('a working dad','un père actif','a working father',None,1,711),
    ('a single mother','une mère célibataire','a single mom',None,2,712),
    ('a single father','un père célibataire','a single dad',None,1,713),
    ('retirees','les retraités',None,None,0,714),
    ('to be called','s''appeler','to be named',None,0,715),
    ('to call','appeler',None,None,0,716),
    ('to go away','s''en aller',None,None,0,717),
    ('to have a good time','s''amuser',None,None,0,718),
    ('to wonder','se demander',None,None,0,719),
    ('to hurry','se dépêcher',None,None,0,720),
    ('to relax','se détendre',None,None,0,721),
    ('to be bored','s''ennuyer',None,None,0,722),
    ('to get along','s''entendre',None,None,0,723),
    ('to apologize to each other','s''excuser','to be sorry','',0,724),
    ('to get angry','se fâcher',None,None,0,725),
    ('to worry','s''inquiéter',None,None,0,726),
    ('to worry about','s''inquiéter de',None,None,0,727),
    ('to move into','s''installer',None,None,0,728),
    ('to be interested in','s''intéresser',None,None,0,729),
    ('to be suspicious of','se méfier de',None,None,0,730),
    ('to begin to','se mettre à',None,None,0,731),
    ('to take care of','s''occuper de',None,None,0,732),
    ('to happen','se passer',None,None,0,733),
    ('to get lost','se perdre',None,None,0,734),
    ('to take a walk','se promener','to stroll',None,0,735),
    ('to recall','se rappeler','to remember','',0,736),
    ('to call back','rappeler','','',0,737),
    ('to realize','se rendre compte',None,None,0,738),
    ('to rest','se reposer','','',0,739),
    ('to feel','se sentir','','',0,740),
    ('to remember','se souvenir',None,None,0,741),
    ('to be located','se trouver',None,None,0,742),
    ('to be mistaken','se tromper',None,None,0,743),
    ('to cheat on','tromper',None,None,0,744),
    ('in my opinion','à mon avis',None,None,0,745),
    ('an app','une application','an application',None,2,746),
    ('a blog','un blog',None,None,1,747),
    ('an account','un compte',None,None,1,748),
    ('a weekly magazine','un hebdomadaire',None,None,1,749),
    ('a diary','un journal intime',None,None,1,750),
    ('a magazine','un magazine',None,None,1,751),
    ('a monthly magazine','un magazine mensuel',None,None,1,752),
    ('a daily newspaper publication','un journal quotidien',None,None,1,753),
    ('a social network','un réseau social',None,None,1,754),
    ('a website','un site Web',None,None,1,755),
    ('a tablet','une tablette','an iPad',None,2,756),
    ('a videoconference','une vidéoconférence',None,None,2,757),
    ('a thought','une pensée',None,None,2,758),
    ('gossip','les potins',None,None,0,759),
    ('a feeling','un sentiment',None,None,1,760),
    ('to subscribe to','s''abonner à',None,None,0,761),
    ('to bother','déranger','to upset',None,0,762),
    ('to express','exprimer',None,None,0,763),
    ('to cry','pleurer',None,None,0,764),
    ('to post online','poster',None,None,0,765),
    ('to narrate','raconter','to tell about',None,0,766),
    ('to regret','regretter','to be sorry about',None,0,767),
    ('to follow','suivre',None,None,0,768),
    ('to touch','toucher','to deeply move',None,0,769),
    ('to check one''s account','vérifier son compte',None,None,0,770),
    ('That sucks!','C''est dommage!','That''s too bad!','',0,771),
    ('It''s not a big deal.','Ce n''est pas grave.','It doesn''t matter., No worries.',None,0,772),
    ('Finally!','Enfin!',None,None,0,773),
    ('Great!','Génial!','Awesome!','Formidable!',0,774),
    ('Marvelous!','Merveilleux!','Wonderful!, Super!','Super!',0,775),
    ('from time to time','de temps en temps',None,None,0,776),
    ('most of the time','la plupart du temps',None,None,2,777),
    ('all the time','tout le temps',None,None,0,778),
    ('already','déjà',None,None,0,779),
    ('still','encore',None,None,0,780),
    ('always','toujours',None,None,0,781),
    ('none','ne aucun','not any','ne aucune',0,782),
    ('never','ne jamais',None,None,0,783),
    ('neither nor','ne ni ni',None,None,0,784),
    ('not at all','ne pas du tout',None,None,0,785),
    ('not yet','ne pas encore',None,None,0,786),
    ('no one','ne personne','nobody',None,0,787),
    ('no longer','ne plus','not anymore, no more',None,0,788),
    ('only','ne que',None,None,0,789),
    ('nothing','ne rien','not anything',None,0,790),
    ('to know oneself','se connaître','to know each other',None,0,791),
    ('to hate oneself','se détester','to hate each other',None,0,792),
    ('to argue with each other','se disputer',None,None,0,793),
    ('to kiss each other','s''embrasser',None,None,0,794),
    ('to get upset','s''énerver',None,None,0,795),
    ('to get engaged','se fiancer',None,None,0,796),
    ('to get married','se marier',None,None,0,797),
    ('to speak to each other','se parler','to speak to oneself','',0,798),
    ('to leave each other','se quitter','to breakup',None,0,799),
    ('to make up with each other','se réconcilier','to reconcile with each other',None,0,800),
    ('to meet each other','se rencontrer',None,None,0,801),
    ('to telephone each other','se téléphoner','to call each other',None,0,802),
    ('to see each other','se voir','to see oneself',None,0,803)
]