import mariadb

auto_fill_end = 101

numbers = [
    ('zéro', 'zero'),
    ('un', 'one'),
    ('deux', 'two'), 
    ('trois', 'three'), 
    ('quatre', 'four'), 
    ('cinq', 'five'), 
    ('six', 'six'), 
    ('sept', 'seven'),
    ('huit', 'eight'),
    ('neuf', 'nine'),
    ('dix', 'ten'),
    ('onze', 'eleven'),
    ('douze', 'twelve'),
    ('treize', 'thirteen'),
    ('quatorze', 'fourteen'), 
    ('quinze', 'fifteen'),
    ('seize', 'sixteen'),
    ('dix-sept', 'seventeen'),
    ('dix-huit', 'eighteen'),
    ('dix-neuf', 'nineteen'),
    ('vingt', 'twenty'),
    ('vingt et un', 'twenty-one'),
    ('vingt-deux', 'twenty-two'),
    ('vingt-trois', 'twenty-three'),
    ('vingt-quatre', 'twenty-four'),
    ('vingt-cinq', 'twenty-five'),
    ('vingt-six', 'twenty-six'),
    ('vingt-sept', 'twenty-seven'),
    ('vingt-huit', 'twenty-eight'),
    ('vingt-neuf', 'twenty-nine'),
    ('trente', 'thirty'),
    ('trente et un', 'thirty-one'),
    ('trente-deux', 'thirty-two'),
    ('trente-trois', 'thirty-three'),
    ('trente-quatre', 'thirty-four'),
    ('trente-cinq', 'thirty-five'),
    ('trente-six', 'thirty-six'),
    ('trente-sept', 'thirty-seven'),
    ('trente-huit', 'thirty-eight'),
    ('trente-neuf', 'thirty-nine'),
    ('quarante', 'forty'),
    ('quarante et un', 'forty-one'),
    ('quarante-deux', 'forty-two'),
    ('quarante-trois', 'forty-three'),
    ('quarante-quatre', 'forty-four'),
    ('quarante-cinq', 'forty-five'),
    ('quarante-six', 'forty-six'),
    ('quarante-sept', 'forty-seven'),
    ('quarante-huit', 'forty-eight'),
    ('quarante-neuf', 'forty-nine'),
    ('cinquante', 'fifty'),
    ('cinquante et un', 'fifty-one'),
    ('cinquante-deux', 'fifty-two'),
    ('cinquante-trois', 'fifty-three'),
    ('cinquante-quatre', 'fifty-four'),
    ('cinquante-cinq','fifty-five'),
    ('cinquante-six', 'fifty-six'),
    ('cinquante-sept', 'fifty-seven'),
    ('cinquante-huit', 'fifty-eight'),
    ('cinquante-neuf', 'fifty-nine'),
    ('soixante', 'sixty'),
    ('soixante et un', 'sixty-one'),
    ('soixante-deux', 'sixty-two'),
    ('soixante-trois', 'sixty-three'),
    ('soixante-quatre', 'sixty-four'),
    ('soixante-cinq', 'sixty-five'),
    ('soixante-six', 'sixty-six'),
    ('soixante-sept', 'sixty-seven'),
    ('soixante-huit', 'sixty-eight'),
    ('soixante-neuf','sixty-nine'),
    ('soixante-dix', 'seventy'),
    ('soixante et onze', 'seventy-one'),
    ('soixante-douze', 'seventy-two'),
    ('soixante-treize', 'seventy-three'),
    ('soixante-quatorze', 'seventy-four'),
    ('soixante-quinze', 'seventy-five'),
    ('soixante-seize', 'seventy-six'),
    ('soixante-dix-sept', 'seventy-seven'),
    ('soixante-dix-huit', 'seventy-eight'),
    ('soixante-dix-neuf', 'seventy-nine'),
    ('quatre-vingts', 'eighty'),
    ('quatre-vingt-un', 'eighty-one'),
    ('quatre-vingt-deux','eighty-two'),
    ('quatre-vingt-trois', 'eighty-three'),
    ('quatre-vingt-quatre','eighty-four'),
    ('quatre-vingt-cinq', 'eighty-five'),
    ('quatre-vingt-six', 'eighty-six'),
    ('quatre-vingt-sept', 'eighty-seven'),
    ('quatre-vingt-huit', 'eighty-eight'),
    ('quatre-vingt-neuf','eighty-nine'),
    ('quatre-vingt-dix', 'ninety'),
    ('quatre-vingt-onze', 'ninety-one'),
    ('quatre-vingt-douze', 'ninety-two'),
    ('quatre-vingt-treize', 'ninety-three'),
    ('quatre-vingt-quatorze', 'ninety-four'),
    ('quatre-vingt-quinze', 'ninety-five'),
    ('quatre-vingt-seize', 'ninety-six'),
    ('quatre-vingt-dix-sept', 'ninety-seven'),
    ('quatre-vingt-dix-huit', 'ninety-eight'),
    ('quatre-vingt-dix-neuf', 'ninety-nine'),
    ('cent', 'one hundred'),
    ('cent un', 'one hundred one'),
    (200, 'deux cents', 'two hundred'),
    (201, 'deux cent un', 'one hundred'),
    (1000, 'mille', 'one thousand'),
    (1001, 'mille un', 'one thousand one'),
    (2000, 'deux mille', 'two thousand'),
    (10000, 'dix mille', 'ten thousand'),
    (100000, 'cent mille', 'one hundred thousand'),
    (1000000, 'un million', 'one million'),
    (1000001, 'un million un', 'one million one'),
    (2000000, 'deux millions', 'two million'),
    (2000001, 'deux millions un', 'two million one'),
    (100000000, 'un milliard', 'one billion'),
    (100000001, 'un milliard un', 'one billion one'),
    (200000000, 'deux milliards', 'two billion'),
    (200000001, 'deux milliards un', 'two billion one'),
]

connection = mariadb.connect(user='undertoe', password='vXXtbewgyyWHMXuqc5nmKN29zk9yaxiM5zJy4CfPf4x85j138hzvEpw9d42HpIp1', host='localhost', port=3306, database='etudamie')
cursor = connection.cursor()
for i, n in enumerate(numbers):
    if i <= auto_fill_end:
        i, french, english = n
    else:
        french, english = n
    cursor.execute('insert into number values (?, ?)', (i, french, english))
connection.commit()
connection.close()